version: '3.1'

services:
  monitor-db:
    container_name: monitor-microservice-db
    image: postgres:16
    environment:
      POSTGRES_USER: monitor_microservice
      POSTGRES_PASSWORD: monitor_microservice
      PGDATA: /data/postgres
    volumes:
      - monitor-db:/data/postgres
    ports:
      - "5229:5432"
    networks:
      - db
    restart: unless-stopped
  zipkin:
    container_name: zipkinmonitor
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

networks:
  db:
    driver: bridge

volumes:
  monitor-db: